name: Django CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12.3" # or your project's version

      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run Migrations
        run: |
          python3 manage.py migrate

      - name: Run Tests
        run: |
          python3 manage.py test

      - name: Run Linter (flake8)
        run: |
          pip install flake8
          flake8 .

      - name: Run Coverage
        run: |
          pip install coverage
          coverage run --source=. manage.py test
          coverage report
